Squash all changes from Nick Alilovic's board support branch into one commit

diff --git a/packages/bsp/common/usr/sbin/armbian-add-overlay b/packages/bsp/common/usr/sbin/armbian-add-overlay
--- a/packages/bsp/common/usr/sbin/armbian-add-overlay
+++ b/packages/bsp/common/usr/sbin/armbian-add-overlay
@@ -7,7 +7,7 @@
 # warranty of any kind, whether express or implied.
 
 if [[ ! -n $1 ]]; then
-	echo >&2 "Usage: $0 <overlay_source_file.dts>"
+	echo >&2 "Usage: $0 <overlay_file.dts OR overlay_file.dtbo>"
 	exit -1
 fi
 
@@ -23,8 +23,10 @@ fi
 
 if [[ $1 == *.dts ]]; then
 	fname=$(basename $1 .dts)
+elif [[ $1 == *.dtbo ]]; then
+	fname=$(basename $1 .dtbo)
 else
-	echo >&2 "Overlay source file name should have the .dts extension"
+	echo >&2 "Overlay file name should have .dts or .dtbo extension"
 	exit -1
 fi
 
@@ -40,48 +42,42 @@ if ! grep -q '^setenv overlay_error' /boot/boot.cmd; then
 	exit -1
 fi
 
-if [[ -d /lib/modules/$(uname -r)/build/scripts/dtc ]]; then
-	if [[ ! -x /lib/modules/$(uname -r)/build/scripts/dtc/dtc ]]; then
-		# Can't use distribution provided (i.e. Bionic) dtc yet
-		# https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/livetree.c?id=bba26a5291c8343101e0296b0e478deb4c9b60b0
-		echo >&2 "Error: kernel headers are not installed properly"
-		echo >&2 "Can't find dtc that supports compiling overlays"
-		echo >&2 "Please install the headers package for kernel $(uname -r)"
-		exit -1
-	else
-		export PATH=/lib/modules/$(uname -r)/build/scripts/dtc/:$PATH
-	fi
-fi
-
-if ! type dtc > /dev/null ; then
-	echo "Error: dtc not found in PATH"
-	echo "Please try to install matching kernel headers"
-	exit -1
-fi
-
-if ! grep -q 'symbols' <(dtc --help) ; then
-	echo "Error: dtc does not support compiling overlays"
-#	echo "Please try to install matching kernel headers"
-	exit -1
-fi
-
 if [[ ! -d /boot/overlay-user ]]; then
 	mkdir -p /boot/overlay-user
 fi
 
-temp_dir=$(mktemp -d)
+if [[ $1 == *.dtbo ]]; then
+	echo "Copying pre-compiled overlay"
+	cp $1 /boot/overlay-user/${fname}.dtbo
+else
+	# Existing DTS compilation logic
+	if [[ -d /lib/modules/$(uname -r)/build/scripts/dtc ]]; then
+		if [[ ! -x /lib/modules/$(uname -r)/build/scripts/dtc/dtc ]]; then
+			echo >&2 "Error: kernel headers are not installed properly"
+			exit -1
+		else
+			export PATH=/lib/modules/$(uname -r)/build/scripts/dtc/:$PATH
+		fi
+	fi
 
-echo "Compiling the overlay"
+	if ! type dtc > /dev/null ; then
+		echo "Error: dtc not found in PATH"
+		exit -1
+	fi
 
-dtc -@ -q -I dts -O dtb -o ${temp_dir}/${fname}.dtbo $1
+	temp_dir=$(mktemp -d)
+	echo "Compiling the overlay"
+	dtc -@ -q -I dts -O dtb -o ${temp_dir}/${fname}.dtbo $1
+	
+	if [[ $? -ne 0 ]]; then
+		echo >&2 "Error compiling the overlay"
+		exit -1
+	fi
 
-if [[ $? -ne 0 ]]; then
-	echo >&2 "Error compiling the overlay"
-	exit -1
+	echo "Copying the compiled overlay file to /boot/overlay-user/"
+	cp ${temp_dir}/${fname}.dtbo /boot/overlay-user/${fname}.dtbo
+	rm -rf ${temp_dir}
 fi
-
-echo "Copying the compiled overlay file to /boot/overlay-user/"
-cp ${temp_dir}/${fname}.dtbo /boot/overlay-user/${fname}.dtbo
 
 if grep -q '^user_overlays=' /boot/armbianEnv.txt; then
 	line=$(grep '^user_overlays=' /boot/armbianEnv.txt | cut -d'=' -f2)
@@ -97,3 +93,4 @@ else
 fi
 
 echo "Reboot is required to apply the changes"
+
